#include "ppu/ppu.hpp"

#include "serialize/serialize.hpp"

namespace snes {

// PPU save-state serialization (phase 7). Mirrors the full render + timing
// state so a loaded state resumes pixel-exactly. The framebuffer itself is
// not saved (it is regenerated by the next frame's render pipeline), nor are
// the interrupt/frame sinks (re-wired by System on construction).

auto Ppu::serialize(Writer& w) const -> void {
  // ---- memory ----
  for (int i = 0; i < 32768; i++) w.u16(vram_[i]);
  for (int i = 0; i < 128; i++) {
    const SpriteObj& o = oamObj_[i];
    w.u16(o.x); w.u8(o.y); w.u8(o.character);
    w.b(o.nameselect); w.b(o.vflip); w.b(o.hflip);
    w.u8(o.priority); w.u8(o.palette); w.b(o.size);
  }
  for (int i = 0; i < 256; i++) w.u16(cgram_[i]);

  // ---- io_ ----
  w.u8(io_.displayBrightness); w.b(io_.displayDisable);
  w.u16(io_.oamBaseAddr); w.u16(io_.oamAddr); w.b(io_.oamPriority);
  w.u8(io_.mode); w.b(io_.bgPriority);
  w.u16(io_.hoffsetMode7); w.u16(io_.voffsetMode7);
  w.u8(io_.vramIncrementSize); w.u8(io_.vramMapping); w.b(io_.vramIncrementMode);
  w.u16(io_.vramAddr);
  w.b(io_.hflipMode7); w.b(io_.vflipMode7); w.u8(io_.repeatMode7);
  w.u16(io_.m7a); w.u16(io_.m7b); w.u16(io_.m7c); w.u16(io_.m7d);
  w.u16(io_.m7x); w.u16(io_.m7y);
  w.u8(io_.cgramAddr); w.b(io_.cgramAddrLatch);
  w.b(io_.interlace); w.b(io_.overscan); w.b(io_.pseudoHires); w.b(io_.extbg);
  w.u16(io_.hcounter); w.u16(io_.vcounter);

  // ---- latch_ ----
  w.u16(latch_.vram); w.u8(latch_.oam); w.u8(latch_.cgram);
  w.u8(latch_.bgofsPPU1); w.u8(latch_.bgofsPPU2); w.u8(latch_.mode7);
  w.b(latch_.counters); w.b(latch_.hcounter); w.b(latch_.vcounter);
  w.u16(latch_.oamAddr); w.u8(latch_.cgramAddr);

  // ---- MDR + state_ ----
  w.u8(ppu1_.version); w.u8(ppu1_.mdr);
  w.u8(ppu2_.version); w.u8(ppu2_.mdr);
  w.b(state_.interlace); w.b(state_.overscan); w.u16(state_.vdisp);

  // ---- layers_ ----
  for (int i = 0; i < 4; i++) {
    const Layer& l = layers_[i];
    w.u8(l.screenSize); w.u16(l.screenAddress); w.u16(l.tileBase);
    w.u8(l.tileSize); w.u8(l.mode);
    w.u8(l.priority[0]); w.u8(l.priority[1]);
    w.b(l.aboveEnable); w.b(l.belowEnable);
    w.u16(l.hscroll); w.u16(l.vscroll);
    w.u8(l.above.priority); w.u8(l.above.palette); w.u8(l.above.paletteGroup);
    w.u8(l.below.priority); w.u8(l.below.palette); w.u8(l.below.paletteGroup);
    w.b(l.mosaic.enable); w.u16(l.mosaic.hcounter); w.u16(l.mosaic.hoffset);
    w.u8(l.mosaic.pixel.priority); w.u8(l.mosaic.pixel.palette); w.u8(l.mosaic.pixel.paletteGroup);
    w.u16(l.opt.hoffset); w.u16(l.opt.voffset);
    for (int t = 0; t < 66; t++) {
      w.u16(l.tiles[t].address); w.u16(l.tiles[t].character);
      w.u8(l.tiles[t].palette); w.u8(l.tiles[t].paletteGroup);
      w.u8(l.tiles[t].priority);
      w.b(l.tiles[t].hmirror); w.b(l.tiles[t].vmirror);
      w.u16(l.tiles[t].data[0]); w.u16(l.tiles[t].data[1]);
      w.u16(l.tiles[t].data[2]); w.u16(l.tiles[t].data[3]);
    }
    w.u8(l.renderingIndex); w.u8(l.pixelCounter);
  }

  // ---- sprites_ ----
  {
    const SpriteEngine& s = sprites_;
    w.b(s.aboveEnable); w.b(s.belowEnable); w.b(s.interlace);
    w.u16(s.tileBase); w.u8(s.nameselect); w.u8(s.baseSize);
    w.u8(s.priority[0]); w.u8(s.priority[1]); w.u8(s.priority[2]); w.u8(s.priority[3]);
    w.b(s.rangeOver); w.b(s.timeOver);
    w.u8(s.firstSprite); w.u8(s.latchedFirst);
    w.u32(s.t.x); w.u32(s.t.y); w.u32(s.t.itemCount); w.u32(s.t.tileCount);
    w.b(s.t.active);
    for (int b = 0; b < 2; b++)
      for (int i = 0; i < 32; i++) { w.b(s.t.item[b][i].valid); w.u8(s.t.item[b][i].index); }
    for (int b = 0; b < 2; b++)
      for (int i = 0; i < 34; i++) {
        w.b(s.t.tile[b][i].valid); w.u16(s.t.tile[b][i].x);
        w.u8(s.t.tile[b][i].priority); w.u8(s.t.tile[b][i].palette);
        w.b(s.t.tile[b][i].hflip); w.u32(s.t.tile[b][i].data);
      }
    w.u8(s.above.priority); w.u8(s.above.palette);
    w.u8(s.below.priority); w.u8(s.below.palette);
  }

  // ---- window_ ----
  {
    auto wl = [&](const WindowMask::Layer& l) {
      w.b(l.oneInvert); w.b(l.oneEnable); w.b(l.twoInvert); w.b(l.twoEnable);
      w.u8(l.mask); w.b(l.aboveEnable); w.b(l.belowEnable);
    };
    wl(window_.bg1); wl(window_.bg2); wl(window_.bg3); wl(window_.bg4); wl(window_.obj);
    w.b(window_.col.oneEnable); w.b(window_.col.oneInvert);
    w.b(window_.col.twoEnable); w.b(window_.col.twoInvert);
    w.u8(window_.col.mask); w.u8(window_.col.aboveMask); w.u8(window_.col.belowMask);
    w.u8(window_.oneLeft); w.u8(window_.oneRight); w.u8(window_.twoLeft); w.u8(window_.twoRight);
    w.u32(window_.x);
    w.b(window_.above.colorEnable); w.b(window_.below.colorEnable);
  }

  // ---- composer_ ----
  {
    const Composer& c = composer_;
    w.b(c.directColor); w.b(c.blendMode); w.b(c.colorMode); w.b(c.colorHalve);
    w.b(c.bg1ColorEnable); w.b(c.bg2ColorEnable); w.b(c.bg3ColorEnable);
    w.b(c.bg4ColorEnable); w.b(c.objColorEnable); w.b(c.backColorEnable);
    w.u8(c.colorRed); w.u8(c.colorGreen); w.u8(c.colorBlue);
    w.u16(c.above.color); w.b(c.above.colorEnable);
    w.u16(c.below.color); w.b(c.below.colorEnable);
    w.b(c.transparent); w.b(c.mathBlendMode); w.b(c.mathColorHalve);
  }

  // ---- mosaic_ ----
  w.u8(mosaic_.size); w.u8(mosaic_.vcounter);

  // ---- timing state ----
  w.u16(dot_); w.u16(scanline_);
  w.u64(frame_); w.u64(renderedFrames_);
  w.b(pendingStart_);
  w.u8(nmitimen_); w.u16(htime_); w.u16(vtime_);
  w.b(vblank_); w.b(irqFlag_); w.b(hblank_); w.b(nmiEdgePrev_); w.b(wrioBit7_);
}

auto Ppu::deserialize(Reader& r) -> void {
  // ---- memory ----
  for (int i = 0; i < 32768; i++) vram_[i] = r.u16();
  for (int i = 0; i < 128; i++) {
    SpriteObj& o = oamObj_[i];
    o.x = r.u16(); o.y = r.u8(); o.character = r.u8();
    o.nameselect = r.b(); o.vflip = r.b(); o.hflip = r.b();
    o.priority = r.u8(); o.palette = r.u8(); o.size = r.b();
  }
  for (int i = 0; i < 256; i++) cgram_[i] = r.u16();

  // ---- io_ ----
  io_.displayBrightness = r.u8(); io_.displayDisable = r.b();
  io_.oamBaseAddr = r.u16(); io_.oamAddr = r.u16(); io_.oamPriority = r.b();
  io_.mode = r.u8(); io_.bgPriority = r.b();
  io_.hoffsetMode7 = r.u16(); io_.voffsetMode7 = r.u16();
  io_.vramIncrementSize = r.u8(); io_.vramMapping = r.u8(); io_.vramIncrementMode = r.b();
  io_.vramAddr = r.u16();
  io_.hflipMode7 = r.b(); io_.vflipMode7 = r.b(); io_.repeatMode7 = r.u8();
  io_.m7a = r.u16(); io_.m7b = r.u16(); io_.m7c = r.u16(); io_.m7d = r.u16();
  io_.m7x = r.u16(); io_.m7y = r.u16();
  io_.cgramAddr = r.u8(); io_.cgramAddrLatch = r.b();
  io_.interlace = r.b(); io_.overscan = r.b(); io_.pseudoHires = r.b(); io_.extbg = r.b();
  io_.hcounter = r.u16(); io_.vcounter = r.u16();

  // ---- latch_ ----
  latch_.vram = r.u16(); latch_.oam = r.u8(); latch_.cgram = r.u8();
  latch_.bgofsPPU1 = r.u8(); latch_.bgofsPPU2 = r.u8(); latch_.mode7 = r.u8();
  latch_.counters = r.b(); latch_.hcounter = r.b(); latch_.vcounter = r.b();
  latch_.oamAddr = r.u16(); latch_.cgramAddr = r.u8();

  // ---- MDR + state_ ----
  ppu1_.version = r.u8(); ppu1_.mdr = r.u8();
  ppu2_.version = r.u8(); ppu2_.mdr = r.u8();
  state_.interlace = r.b(); state_.overscan = r.b(); state_.vdisp = r.u16();

  // ---- layers_ ----
  for (int i = 0; i < 4; i++) {
    Layer& l = layers_[i];
    l.screenSize = r.u8(); l.screenAddress = r.u16(); l.tileBase = r.u16();
    l.tileSize = r.u8(); l.mode = r.u8();
    l.priority[0] = r.u8(); l.priority[1] = r.u8();
    l.aboveEnable = r.b(); l.belowEnable = r.b();
    l.hscroll = r.u16(); l.vscroll = r.u16();
    l.above.priority = r.u8(); l.above.palette = r.u8(); l.above.paletteGroup = r.u8();
    l.below.priority = r.u8(); l.below.palette = r.u8(); l.below.paletteGroup = r.u8();
    l.mosaic.enable = r.b(); l.mosaic.hcounter = r.u16(); l.mosaic.hoffset = r.u16();
    l.mosaic.pixel.priority = r.u8(); l.mosaic.pixel.palette = r.u8(); l.mosaic.pixel.paletteGroup = r.u8();
    l.opt.hoffset = r.u16(); l.opt.voffset = r.u16();
    for (int t = 0; t < 66; t++) {
      l.tiles[t].address = r.u16(); l.tiles[t].character = r.u16();
      l.tiles[t].palette = r.u8(); l.tiles[t].paletteGroup = r.u8();
      l.tiles[t].priority = r.u8();
      l.tiles[t].hmirror = r.b(); l.tiles[t].vmirror = r.b();
      l.tiles[t].data[0] = r.u16(); l.tiles[t].data[1] = r.u16();
      l.tiles[t].data[2] = r.u16(); l.tiles[t].data[3] = r.u16();
    }
    l.renderingIndex = r.u8(); l.pixelCounter = r.u8();
  }

  // ---- sprites_ ----
  {
    SpriteEngine& s = sprites_;
    s.aboveEnable = r.b(); s.belowEnable = r.b(); s.interlace = r.b();
    s.tileBase = r.u16(); s.nameselect = r.u8(); s.baseSize = r.u8();
    s.priority[0] = r.u8(); s.priority[1] = r.u8(); s.priority[2] = r.u8(); s.priority[3] = r.u8();
    s.rangeOver = r.b(); s.timeOver = r.b();
    s.firstSprite = r.u8(); s.latchedFirst = r.u8();
    s.t.x = r.u32(); s.t.y = r.u32(); s.t.itemCount = r.u32(); s.t.tileCount = r.u32();
    s.t.active = r.b();
    for (int b = 0; b < 2; b++)
      for (int i = 0; i < 32; i++) { s.t.item[b][i].valid = r.b(); s.t.item[b][i].index = r.u8(); }
    for (int b = 0; b < 2; b++)
      for (int i = 0; i < 34; i++) {
        s.t.tile[b][i].valid = r.b(); s.t.tile[b][i].x = r.u16();
        s.t.tile[b][i].priority = r.u8(); s.t.tile[b][i].palette = r.u8();
        s.t.tile[b][i].hflip = r.b(); s.t.tile[b][i].data = r.u32();
      }
    s.above.priority = r.u8(); s.above.palette = r.u8();
    s.below.priority = r.u8(); s.below.palette = r.u8();
  }

  // ---- window_ ----
  {
    auto wl = [&](WindowMask::Layer& l) {
      l.oneInvert = r.b(); l.oneEnable = r.b(); l.twoInvert = r.b(); l.twoEnable = r.b();
      l.mask = r.u8(); l.aboveEnable = r.b(); l.belowEnable = r.b();
    };
    wl(window_.bg1); wl(window_.bg2); wl(window_.bg3); wl(window_.bg4); wl(window_.obj);
    window_.col.oneEnable = r.b(); window_.col.oneInvert = r.b();
    window_.col.twoEnable = r.b(); window_.col.twoInvert = r.b();
    window_.col.mask = r.u8(); window_.col.aboveMask = r.u8(); window_.col.belowMask = r.u8();
    window_.oneLeft = r.u8(); window_.oneRight = r.u8(); window_.twoLeft = r.u8(); window_.twoRight = r.u8();
    window_.x = r.u32();
    window_.above.colorEnable = r.b(); window_.below.colorEnable = r.b();
  }

  // ---- composer_ ----
  {
    Composer& c = composer_;
    c.directColor = r.b(); c.blendMode = r.b(); c.colorMode = r.b(); c.colorHalve = r.b();
    c.bg1ColorEnable = r.b(); c.bg2ColorEnable = r.b(); c.bg3ColorEnable = r.b();
    c.bg4ColorEnable = r.b(); c.objColorEnable = r.b(); c.backColorEnable = r.b();
    c.colorRed = r.u8(); c.colorGreen = r.u8(); c.colorBlue = r.u8();
    c.above.color = r.u16(); c.above.colorEnable = r.b();
    c.below.color = r.u16(); c.below.colorEnable = r.b();
    c.transparent = r.b(); c.mathBlendMode = r.b(); c.mathColorHalve = r.b();
    c.line = nullptr;
  }

  // ---- mosaic_ ----
  mosaic_.size = r.u8(); mosaic_.vcounter = r.u8();

  // ---- timing state ----
  dot_ = r.u16(); scanline_ = r.u16();
  frame_ = r.u64(); renderedFrames_ = r.u64();
  pendingStart_ = r.b();
  nmitimen_ = r.u8(); htime_ = r.u16(); vtime_ = r.u16();
  vblank_ = r.b(); irqFlag_ = r.b(); hblank_ = r.b(); nmiEdgePrev_ = r.b(); wrioBit7_ = r.b();
}

}  // namespace snes
